apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080  